# Generated by Django 4.2.16 on 2024-09-19 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('category', models.CharField(max_length=240, verbose_name='Category')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('unique_code', models.CharField(max_length=50, verbose_name='unique_code')),
                ('brand', models.CharField(max_length=240, verbose_name='Brand')),
                ('image', models.CharField(max_length=240, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='User_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=8000)),
                ('overview', models.CharField(max_length=1000)),
                ('avg_sentiment', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review_count', models.DecimalField(decimal_places=0, max_digits=5)),
                ('postive_count', models.DecimalField(decimal_places=0, max_digits=5)),
                ('negative_count', models.DecimalField(decimal_places=0, max_digits=5)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Product_Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=8000)),
                ('sentiment', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sentiment_label', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=2)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
