# Generated by Django 4.2.14 on 2024-09-20 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product_summary",
            old_name="postive_count",
            new_name="positive_count",
        ),
    ]
