# Generated by Django 4.2.14 on 2024-09-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_data_source",
            name="category",
            field=models.CharField(
                default="111", max_length=50, verbose_name="category"
            ),
            preserve_default=False,
        ),
    ]
