# Generated by Django 4.2.14 on 2024-08-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unique_code",
            field=models.CharField(
                default="1111", max_length=50, verbose_name="unique_code"
            ),
            preserve_default=False,
        ),
    ]
