# Generated by Django 4.2.14 on 2024-08-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="url",
            field=models.CharField(max_length=500, verbose_name="URL"),
        ),
    ]
