# Generated by Django 4.2.14 on 2024-08-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_product_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="NAN", max_length=240, verbose_name="Brand"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product_reviews",
            name="sentiment_label",
            field=models.CharField(default="Neutral", max_length=10),
            preserve_default=False,
        ),
    ]
