# Generated by Django 4.2.16 on 2024-09-20 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_reviews_rating'),
        ('api', '0002_rename_postive_count_product_summary_positive_count'),
    ]

    operations = [
    ]
