# Generated by Django 4.2.14 on 2024-08-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_product_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="NAN", max_length=240, verbose_name="Brand"),
            preserve_default=False,
        ),
    ]
