# Generated by Django 4.2.14 on 2024-08-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_product_description_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_reviews",
            name="sentiment_label",
            field=models.CharField(default="NAN", max_length=10),
            preserve_default=False,
        ),
    ]
