# Generated by Django 4.2.14 on 2024-08-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_product_description_product_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_summary",
            name="overview",
            field=models.CharField(default="NA", max_length=1000),
            preserve_default=False,
        ),
    ]
