# Generated by Django 4.2.14 on 2024-08-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_product_summary_overview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product_summary",
            options={"ordering": ("-date",)},
        ),
        migrations.AlterField(
            model_name="product_summary",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
