name: Test and Deploy

on:
  push:
    branches:
      - Test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and Start Docker
        run: |
          docker-compose up -d --build

      - name: Debug container file structure
        run: docker-compose exec -T vopop-backend bash -c "ls -l /"

      - name: Run tests inside Docker container
        run: |
          sudo pwd
          docker-compose exec -T vopop-backend bash -c "ls -al"
          docker-compose exec -T vopop-backend bash -c " cd test/backendTest && python -m unittest discover -p '*.py' "

      - name: Display logs
        if: failure()
        run: |
          docker-compose logs

      - name: Shut docker down
        if: always()
        run: |
          docker-compose down

  deploy:
    needs: test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions@github.com'

      - name: Authenticate with GitHub
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/LucaRosic/VoPop.git

      - name: Fetch all branches
        run: git fetch --all

      - name: Pull latest changes from main
        run: |
          git checkout main
          git pull origin main

      - name: Push to main
        run: |
          git checkout -b temp-deploy
          git merge --no-ff --allow-unrelated-histories -X ours Test
          git push origin temp-deploy:main
